---
# Playbook to apply the basic configuration to the system to connect to docker
# registry.

########################################################################
- name: Additional bare metal configuration --  all node
  hosts: all
  vars:
    ansible_ssh_user: root
  tasks:
    - name: Make sure cert directory exists
      file:
        path: "/etc/docker/certs.d/{{ docker_registry }}:{{ docker_registry_port }}"
        state: directory
        recurse: yes
    - name: Get cert for registry
      copy:
        src: data/registry.crt
        dest: "/etc/docker/certs.d/{{ docker_registry }}:{{ docker_registry_port }}/registry.crt"


- name: Additional bare metal configuration -- GPU Nodes
  hosts: gpu_server
  vars:
    ansible_ssh_user: root
  roles:
    - gpu_node

########################################################################
- name: Generate local security relevant data
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: generate ssh keys for ansible interface
      openssh_keypair:
        path: "{{ playbook_dir }}/data/id_rsa"
  tags:
    - build


########################################################################
- name: setup control server
  hosts: dev_server
  gather_facts: no
  roles:
    - docker_registry
    - redis_storage
      #    - dhcp
    - edd_master_controller
    - effelsberg_scpi_interface
    - logspout



########################################################################
- name: setup worker nodes
  hosts: gpu_server
  gather_facts: no
  roles:
    - edd_base
    - ansible_interface
    - logspout
