---
# Playbook to apply the basic configuration to the system to connect to docker
# registry.

- hosts: dev_server
  roles:
    - docker_registry
    - redis_storage
    - edd_master_controller

- hosts: all
  vars:
    ansible_ssh_user: root
  tasks:
    - name: Make sure cert directory exists
      file:
        path: "/etc/docker/certs.d/{{ docker_registry }}:{{ docker_registry_port }}"
        state: directory
        recurse: yes
    - name: Get cert for registry
      copy:
        src: data/registry.crt
        dest: "/etc/docker/certs.d/{{ docker_registry }}:{{ docker_registry_port }}/registry.crt"

# build base docker image
- hosts: gpu_server[0]
  roles:
    - edd_base
