---
all:
  vars:
    redis_storage: "{{ groups['dev_server'][0] }}"
    docker_registry: "{{ groups['dev_server'][0] }}"
    docker_registry_port: "5000"
    docker_registry_data_path: "/media/scratch/docker_registry/"
    docker_runtime: ""
    devices_networking: ""
    # The subnet to which the katcp server are listening to for control
    # connections
    edd_subnet: "0.0.0.0"
    # Port on which to reach the master controller
    #master_controller_port: "1239"
    # ports which can be assigned to katcp servers for products
    edd_katcp_ports:
      - 7147
      - 7148
      - 7149
      - 7150

    fact_caching: redis
    fact_caching_connection: edd01:6379:0

    #cache: yes
    #cache_plugin: redis
    #cache_timeout: 7200
    #cache_connection: edd01:6379:0

  children:
    dev_server:
      hosts:
        edd01

    gpu_server:
      hosts:
        edd[00:01]
      vars:
        devices_networking:
          - "/dev/infiniband/rdma_cm"
          - "/dev/infiniband/issm0"
          - "/dev/infiniband/ucm0"
          - "/dev/infiniband/umad0"
          - "/dev/infiniband/uverbs0"
          - "/dev/infiniband/issm1"
          - "/dev/infiniband/ucm1"
          - "/dev/infiniband/umad1"
          - "/dev/infiniband/uverbs1"
          - "/dev/infiniband/issm2"
          - "/dev/infiniband/ucm2"
          - "/dev/infiniband/umad2"
          - "/dev/infiniband/uverbs2"
        docker_runtime:
            nvidia

