---
all:
  vars:
    redis_storage: "{{ groups['dev_server'][0] }}"
    docker_registry: "{{ groups['dev_server'][0] }}"
    docker_registry_port: "5000"
    ansible_python_interpreter: auto_legacy_silent
    docker_registry_data_path: "/media/scratch/docker_registry/"
    docker_runtime: ""
    log_server: "effgraylog.mpifr-bonn.mpg.de:12201"
    devices_networking: ""
    # base path as used for additional data definitions
    base_path: "{{ playbook_dir }}"
    # The subnet to which the katcp server are listening to for control
    # connections
    edd_subnet: "0.0.0.0"
    # port for master controller ansible ssh conenctions
    edd_ansible_port: 2222
    # Port on which to reach the master controller
    #master_controller_port: "1239"
    # ports which can be assigned to katcp servers for products
    edd_katcp_port_range_start: 7147
    edd_katcp_port_range_stop: 7199

    effelsberg_scpi_port: 5025

    #cache: yes
    #cache_plugin: redis
    #cache_timeout: 7200
    #cache_connection: edd01:6379:0

  children:
    dev_server:
      hosts:
        edd01

    gpu_server:
      hosts:
        edd[00:01]
      vars:
        devices_networking:
          - "/dev/infiniband/rdma_cm"
          - "/dev/infiniband/issm0"
          - "/dev/infiniband/ucm0"
          - "/dev/infiniband/umad0"
          - "/dev/infiniband/uverbs0"
          - "/dev/infiniband/issm1"
          - "/dev/infiniband/ucm1"
          - "/dev/infiniband/umad1"
          - "/dev/infiniband/uverbs1"
          - "/dev/infiniband/issm2"
          - "/dev/infiniband/ucm2"
          - "/dev/infiniband/umad2"
          - "/dev/infiniband/uverbs2"
        docker_runtime:
            nvidia

