---
    - get_url:
        url: "{{ driver_url }}"
        dest: /tmp
        mode: +x
    - service:
        name: docker
        state: stopped
    - modprobe:
        name: "{{ item }}"
        state: absent
      with_items:
        - nvidia_drm
        - nvidia_modeset
        - nvidia_uvm
        - nvidia
    - command: "/tmp/{{ installer_file }} -a -s"
    - command: "nvidia-persistenced"
    - service:
        name: docker
        state: started
