---
  - name: Launch gated docker container
    #tags: start
    docker_container:
      name: GATED_PRODUCTION
      image: edd_gated:latest
      state: started            # ensure that is running
      privileged: yes
      auto_remove: yes
      runtime: nvidia
      devices:
        "{{ devices_networking }}"
      network_mode: host
      capabilities:
        - "IPC_LOCK"
      detach: yes
      command: python /usr/local/lib/python2.7/dist-packages/mpikat-0.1-py2.7.egg/mpikat/effelsberg/edd/pipeline/GatedSpectrometerPipeline.py

    #  - name: Stop gated docker container
    #    tags: stop
    #    docker_container:
    #      name: GATED_PRODUCTION
    #      state: stopped
