---
  - name: Launch gated docker container
    #tags: start
    docker_container:
      name: GATED_PRODUCTION
      image: "{{ docker_registry }}/edd_gated:latest"
      state: started            # ensure that is running
      privileged: yes
      auto_remove: yes
      runtime: nvidia
      devices:
        "{{ devices_networking }}"
      network_mode: host
      capabilities:
        - "IPC_LOCK"
      detach: yes
      command: python /usr/local/lib/python2.7/dist-packages/mpikat-0.1-py2.7.egg/mpikat/effelsberg/edd/pipeline/GatedSpectrometerPipeline.py


  - name: Build and push
    run_once: true    # only need to run on one machine
    tags:
      - never         # only run when build tag is specified
      - build
    docker_image:
      name: edd_gated
      build:
        path: "{{ role_path }}/files/docker/"

    #  - name: Stop gated docker container
    #    tags: stop
    #    docker_container:
    #      name: GATED_PRODUCTION
    #      state: stopped
