---
 - name: Fits interface
   import_role:
      name: common
   vars:
      image_name: edd_fits_interface
      container_name: FITS_INTERFACE_PRODUCTION
      container_cmd: "/usr/bin/python /usr/local/lib/python2.7/dist-packages/mpikat-0.1-py2.7.egg/mpikat/effelsberg/edd/spead2_fi_server.py --host={{ edd_subnet }} --port={{ bind_port }}"
