---
- name: Build dhcp image
  block:
  - name: Create build directory
    tempfile:
      state: directory
      suffix: temp
    register: build_directory

  - name: Copy files
    copy:
      src: "{{ item }}"
      dest: "{{ build_directory.path }}/"
    with_fileglob:
      - files/*

  - template:
      src: "{{ item }}"
      dest: "{{ build_directory.path }}/"
    with_fileglob:
      - templates/*



  - name: build and push
    docker_image:
      name: "{{ docker_registry }}:{{ docker_registry_port }}/dhcp"
      source: build
      force_source: true
      build:
        pull: yes
        path: "{{ build_directory.path }}"
        nocache: true
      push: yes

  - name: remove the temporary directory
    file:
      path: "{{ build_directory.path }}"
      state: absent
    when: build_directory.path is defined

  run_once: true    # only need to run on one machine
  tags:
    - never         # only run when build tag is specified
    - build




- name: Launch dhcpd
  docker_container:
    name: "edd_dhcpd"
    image: "{{ docker_registry }}:{{ docker_registry_port }}/dhcp:latest"
    detach: yes
    state: started            # ensure that is running
    network_mode: host        # host as need access to network for introspection
    restart_policy: always
    restart: true
    pull: yes


- name: Stop dhcpd
  block:
    - docker_container:
        name: "edd_dhcpd"
        state: absent
  tags:
    - never
    - stop
