---
#
# Pipeline is based on pulsar_base image that is buidld with --tags=buildbase
# to speed up development
#
- name: Build pulsar base docker image
  block:
    - name: Remove image
      docker_image:
        name : "{{ docker_registry }}:{{ docker_registry_port }}/pulsar_base"
        state: absent
        force_absent: yes

    - name: Create build directory
      tempfile:
        state: directory
        suffix: temp
      register: build_directory

    - name: Copy dockerfile from template
      template:
        src: Dockerfile_pulsarbase
        dest: "{{ build_directory.path }}/Dockerfile"

    - name: Copy additional build files
      copy:
        remote_src: yes
        src: "{{ additional_build_files.path }}/"
        dest: "{{ build_directory.path }}/"
      when: additional_build_files is defined

    - name: Build and push image
      docker_image:
        name : "{{ docker_registry }}:{{ docker_registry_port }}/pulsar_base"
        source: build
        force_source: true
        build:
          path: "{{ build_directory.path }}"
          pull: yes
          nocache: true
        push: yes

    - name: remove the temporary directory
      file:
        path: "{{ build_directory.path }}"
        state: absent
      when: build_directory.path is defined

  run_once: true    # only need to run on one machine
  tags:
    - never         # only run when build tag is specified
    - buildbase



- name: Pulsar Pipeline
  import_role:
     name: common
  vars:
     image_name: edd_pulsar
     default_container_name: pulsar_pipeline
     container_cmd: "/usr/bin/python /usr/local/lib/python2.7/dist-packages/mpikat-0.1-py2.7.egg/mpikat/effelsberg/edd/pipeline/EddPulsarPipeline.py  --host={{ edd_subnet }} --port={{ bind_port }}"

- name: Copy epta files
  copy:
    src: "{{ epta_directory }}/"
    dest: "{{ data_dir }}/{{ epta_directory }}"
