---
- name: Check for custom vs default container names
  block:
    - set_fact:
        default_container_name : "{{ image_name }}"
      when: default_container_name is not defined
    - set_fact:
        container_name: "{{ default_container_name }}"
      when: container_name is not defined
    - set_fact:
        edd_container: "{{ {} }}"
      when: edd_container is not defined
    - set_fact:
        container_env: "{{ {} }}"
      when: container_env is not defined
  tags:
    - always


- name: Build image  "{{ image_name }}"
  include_tasks: build_tasks.yml
  run_once: true    # only need to run on one machine
  tags:
    - never         # only run when build tag is specified
    - build

- name: Launch EDD docker container "{{ image_name }}"
  include_tasks: launch_tasks.yml



- name: Stop EDD docker container "{{ image_name }}"
  block:
    - docker_container:
        name: "{{ container_name }}"
        state: absent
    - set_fact:
        edd_container: '{{ edd_container | dict2items | rejectattr( "key", "equalto", container_name )|list|items2dict }}'
        cacheable: true
  tags:
    - never
    - stop
