---
- name: Launch EDD docker container "{{ image_name }}"
  block:
    - file:
        path: "{{ data_dir }}"
        state: directory
        mode: '0777'
    - acl:
        path: "{{ data_dir }}"
        default: yes
        recursive: yes
        etype: mask
        permissions: rwx
        state: present

    - docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_registry }}:{{ docker_registry_port }}/{{ image_name }}:latest"
        state: started            # ensure that is running
        privileged: yes
        auto_remove: yes
        runtime: "{{ docker_runtime }}"
        devices:
          "{{ devices_networking }}"
        network_mode: host
        capabilities:
          - "IPC_LOCK"
        volumes:
          - "{{ data_dir }}:/mnt:rw"
        detach: yes
    - set_fact:
        current_edd_container: "{{ container_name }}"
        current_data_directory: "{{ data_dir }}"


- name: Stop EDD docker container "{{ image_name }}"
  block:
    - docker_container:
        name: "{{ container_name }}"
        state: absent
    - set_fact:
        current_edd_container: "NONE"
  tags:
    - never
    - stop


- name: Build docker image "{{ image_name }}"
  block:
  - name: Remove image
    docker_image:
      name: "{{ docker_registry }}:{{ docker_registry_port }}/{{ image_name }}"
      state: absent
      force_absent: yes

  - name: Create build directory
    tempfile:
      state: directory
      suffix: temp
    register: build_directory

  - name: Copy dockerfile from template
    template:
      src: Dockerfile
      dest: "{{ build_directory.path }}/Dockerfile"

  - name: Build and push image
    docker_image:
      name: "{{ docker_registry }}:{{ docker_registry_port }}/{{ image_name }}"
      source: build
      force_source: true
      build:
        path: "{{ build_directory.path }}"
        pull: yes
      push: yes

    #- name: clean up build directory
    #- file:
    #-   path: "{{ build_directory.path }}"
    #-   state: absent
  run_once: true    # only need to run on one machine
  tags:
    - never         # only run when build tag is specified
    - build


