---
- name: Launch EDD docker container "{{ image_name }}"
  #tags: start
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_registry }}/{{ image_name }}:latest"
    state: started            # ensure that is running
    privileged: yes
    auto_remove: yes
    runtime: nvidia
    devices:
      "{{ devices_networking }}"
    network_mode: host
    capabilities:
      - "IPC_LOCK"
    detach: yes


- name: Build docker image "{{ image_name }}"
  block:
  - name: Create build directory
    tempfile:
      state: directory
      suffix: temp
    register: build_directory

  - name: Copy dockerfile from template
    template:
      src: Dockerfile
      dest: "{{ build_directory.path }}/Dockerfile"

  - name: build and push 
    docker_image:
      name: "{{docker_registry}}/{{image_name}}"
      build:
        path: "{{ build_directory.path }}"
      push: yes

    #- name: clean up build directory
    #- file:
    #-   path: "{{ build_directory.path }}"
    #-   state: absent
  run_once: true    # only need to run on one machine
  tags:
    - never         # only run when build tag is specified
    - build


